language: python
python:
- 3.6
matrix:
  fast_finish: true
  include:
  - env: BROWSER="Firefox" WEB_DRIVER="firefox"
  - env: BROWSER="Chrome" WEB_DRIVER="chrome"
  - env: BROWSER="Opera" WEB_DRIVER="opera"
before_install:
  - pip install poetry
install:
  - poetry install
  - mkdir bin && PATH=$PATH:`pwd`/bin/
  - webdrivermanager install ${WEB_DRIVER} bin/
script:
  - robot --variable browser:${BROWSER} test_shazi.info.robot
notifications:
  email: false
